### ISSUE TITLE
Test suite fails (because of hash randomization?)

### ISSUE THREAD

**Issue by eserte** [yanick/MooseX-Attribute-Handles-Expand#1]
See http://matrix.cpantesters.org/?dist=MooseX-Attribute-Handles-Expand%200.0.1 --- fails happen only for perl >= 5.18, an indication for a hash randomization problem.

**Comment by yanick** [comment]
Ah, even if not lazy, the defaults are not set in the order of their declarations. Interesting. :-)

Thanks!
